name: bookington_v2_2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
